"""Adiciona forma_pagamento e valor_entregue em Pedidos

Revision ID: 9bd56617c596
Revises: 3af07fd60a5a
Create Date: 2025-04-07 14:44:32.962828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bd56617c596'
down_revision = '3af07fd60a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_entregue', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('observacao',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('forma_pagamento',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('forma_pagamento',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=True)
        batch_op.alter_column('observacao',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(collation='utf8mb4_general_ci'),
               nullable=True)
        batch_op.drop_column('valor_entregue')

    # ### end Alembic commands ###
